apiVersion: v1
kind: Service
metadata:
  name: webapp-service-service
  labels:
    app: webapp-service
spec:
  type: LoadBalancer
  selector:
    app: webapp-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-service-deployment
  labels:
    app: webapp-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp-service
  template:
    metadata:
      labels:
        app: webapp-service
    spec:
      containers:
      - name: webapp-service-eks-container
        # The $REPOSITORY_URI and $IMAGE_TAG placeholders will be replaced by actual values supplied by the build action in your workflow
        image: $REPOSITORY_URI:$IMAGE_TAG
        ports:
        - containerPort: 80
