apiVersion: v1
kind: Service
metadata:
  name: apache-web-server-service
  labels:
    app: apache-web-server
spec:
  type: LoadBalancer
  selector:
    app: apache-web-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-web-server-deployment
  labels:
    app: apache-web-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apache-web-server
  template:
    metadata:
      labels:
        app: apache-web-server
    spec:
      containers:
      - name: apache-web-server-eks-container
        # The $REPOSITORY_URI and $IMAGE_TAG placeholders will be replaced by actual values supplied by the build action in your workflow
        image: $REPOSITORY_URI:$IMAGE_TAG
        ports:
        - containerPort: 80
